Better error handling.

diff --git a/config/sweetie_bot_proto2_deploy/scripts/store-joint-trajectories b/config/sweetie_bot_proto2_deploy/scripts/store-joint-trajectories
--- a/config/sweetie_bot_proto2_deploy/scripts/store-joint-trajectories
+++ b/config/sweetie_bot_proto2_deploy/scripts/store-joint-trajectories
@@ -1,14 +1,20 @@
 #!/bin/sh
+PKG=sweetie_bot_proto2_movements
+
 if [ -z $1 ]; then
 	echo "Usage:"
 	echo "    $ `basename $0` load|save"
 	echo 
-	echo "Load joint trajectories from sweetie_bot_proto2_movements package to /joint_trajectory namespace."
+	echo "Load joint trajectories from '$PKG' package to 'joint_trajectory' namespace."
 	echo "or"
-	echo "save joint trajectories from /joint_trajectory namespace to sweetie_bot_proto2_movements package."
+	echo "save joint trajectories from 'joint_trajectory' namespace to '$PKG' package."
 	echo
 	exit 0
 fi
 
-#echo "Invoke: rosrun sweetie_bot_deploy store $1 /joint_trajectory \`rospack find sweetie_bot_proto2_movements\`/joint_trajectories"
-rosrun sweetie_bot_deploy store $1 /joint_trajectory "`rospack find sweetie_bot_proto2_movements`/joint_trajectories"
+JSON_PATH=`rospack find $PKG`/joint_trajectories
+if [ $? -ne 0 -o ! -d "$JSON_PATH" ]; then
+	echo "$0: Unable to find directory 'joint_trajectories' in '$PKG' package."
+	exit 1
+fi
+rosrun sweetie_bot_deploy store $1 joint_trajectory $JSON_PATH
